spring:
  application:
    name: Jaxws

  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: postgres
  
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
 
#server:
 # port: 3030